---

title: Holotable
email: info@holotable.com
description: Holotable
baseurl: ""
url: ""
twitter_username: swccgpc
github_username:  swccgpc

plugins:
  - jekyll-feed

include:
  - "_pages"
  - "_redirects"


downloadables:
  windows:
    holotable:
      url: "https://res.starwarsccg.org/holotable/windows/holotable-0.9.9_install.exe"
      name: "Holotable 0.9.9"
      description: "Holotable 0.9.9 contains changes for the virtual card reset of 2014.<br /><br />Holodeck 0.3.9 is a bug fix release that prevents a crash when adding a new card to a deck while it is sorted by card name."
    largeimages:
      url: "https://res.starwarsccg.org/holotable/windows/holotable-large_images_postreset.exe"
      name: "Large images (post-reset)"
    update:
      url: "https://res.starwarsccg.org/holotable/windows/holotable-0.9.9_update.exe"
      name: "Holotable 0.9.9 update"
    gtk2:
      url: "https://res.starwarsccg.org/holotable/windows/gtk-2.12.9-win32-2.exe"
      name: "gtk 2.12.9"

  linux:
    holotable:
      url: "https://res.starwarsccg.org/holotable/linux/holotable-0.9.9_install_linux.tar.bz2"
      name: "Linux Holotable 0.9.9"
      description: "Holotable 0.9.9 contains changes for the virtual card reset of 2014.<br /><br />Holodeck 0.3.9 is a bug fix release that prevents a crash when adding a new card to a deck while it is sorted by card name."
    largeimages:
      url: "https://res.starwarsccg.org/holotable/linux/holotable-large_images_postreset.tar.bz2"
      name: "Linux large images (post-reset)"
    update:
      url: "https://res.starwarsccg.org/holotable/linux/holotable-0.9.9_update_linux.tar.bz2"
      name: "Linux Holotable 0.9.9 update"

