---

name: build and deploy holotable website

on: 
  push: 
    branches: 
      - main

jobs:
  deploy-holotable-website: 
    runs-on: "ubuntu-latest"
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@main
      - run: "sleep 5"
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: jekyll build
        run: |+
          mkdir _news_indexes ; true
          echo
          echo "Make _news_indexes"
          echo
          ruby _make_posts_indexes.rb

      - name: Set up Jekyll
        uses: helaili/jekyll-action@v2
        with:
          jekyll_src: ./
          build_only: true

      - name: Configure AWS
        run: |
          export AWS_ROLE_ARN=arn:aws:iam::230787692442:role/githuboidc-holotable-website
          export AWS_WEB_IDENTITY_TOKEN_FILE=/tmp/awscreds
          export AWS_DEFAULT_REGION=us-east-2
          #
          echo AWS_WEB_IDENTITY_TOKEN_FILE=$AWS_WEB_IDENTITY_TOKEN_FILE >> $GITHUB_ENV
          echo AWS_ROLE_ARN=$AWS_ROLE_ARN >> $GITHUB_ENV
          echo AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION >> $GITHUB_ENV
          #
          curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r '.value' > $AWS_WEB_IDENTITY_TOKEN_FILE
      - name: sts check
        run: "aws sts get-caller-identity"

      - name: s3_website push
        run: |
          echo
          echo "Install s3_website"
          echo
          sudo gem install s3_website
          echo
          echo "s3_website push"
          echo
          s3_website push







