---

name: build and deploy holotable website

on: 
  push: 
    branches: 
      - master

jobs:
  deploy-vkit: 
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@master

      - name: gem install jekyll
        run: gem install jekyll

      - name: gem install s3_website
        run: gem install s3_website

      - name: jekyll build
        run: |+
          mkdir _news_indexes ; true
          ruby _make_posts_indexes.rb
          jekyll build
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: s3_website push
        run: s3_website push
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}







