---

name: build and deploy holotable website

on: 
  push: 
    branches: 
      - main

jobs:
  deploy-holotable-website: 
    runs-on: "ubuntu-latest"
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@main
      - run: "sleep 5"

      - name: Set up Ruby 2.6
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: jekyll build
        run: |+
          mkdir _news_indexes ; true
          echo
          echo "Make _news_indexes"
          echo
          ruby _make_posts_indexes.rb

      - name: Set up Jekyll
        uses: helaili/jekyll-action@v2
        with:
          jekyll_src: ./
          build_only: true

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: "arn:aws:iam::230787692442:role/githuboidc-holotable-website"
          role-session-name: "holotableWebsiteWorkflow"
          aws-region: "us-east-2"

      - name: sts check
        run: "aws sts get-caller-identity"

      - name: s3_website push
        run: |
          echo
          echo "Install s3_website"
          echo
          sudo gem install s3_website
          echo
          echo "s3_website push"
          echo
          s3_website push







