---

name: build and deploy holotable website

on: 
  push: 
    branches: 
      - main

jobs:
  deploy-holotable-website: 
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@main

      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: jekyll build
        run: |+
          mkdir _news_indexes ; true
          echo
          echo "Make _news_indexes"
          echo
          ruby _make_posts_indexes.rb

      - name: Set up Jekyll
        uses: helaili/jekyll-action@v2
        with:
          jekyll_src: ./
          build_only: true

      - name: s3_website push
        run: |
          echo
          echo "Install s3_website"
          echo
          sudo gem install s3_website
          echo
          echo "s3_website push"
          echo
          s3_website push
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}







