---

name: build and deploy holotable website

on: 
  push: 
    branches: 
      - main

jobs:
  deploy-holotable-website: 
    runs-on: "ubuntu-latest"
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@main
      - run: "sleep 5"

      - name: Set up Ruby 3.0
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: jekyll build
        run: |+
          mkdir _news_indexes ; true
          echo
          echo "Make _news_indexes"
          echo
          ruby _make_posts_indexes.rb
          bundle
          bundle exec jekyll build

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: "arn:aws:iam::230787692442:role/githuboidc-holotable-website"
          role-session-name: "holotableWebsiteWorkflow"
          aws-region: "us-east-2"

      - name: sts check
        run: "aws sts get-caller-identity"

      - name: s3_website push
        run: |
          aws --profile=swccg-production s3 sync _site/ s3://holotable.starwarsccg.org/
          aws --profile=swccg-production cloudfront create-invalidation --distribution-id E2YAV8XKR86PXW  --paths "/" "/*"







